# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/renan/cmake-3.6.1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/renan/cmake-3.6.1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/renan/stm32f4-discovery-cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/renan/stm32f4-discovery-cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/renan/cmake-3.6.1-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/renan/cmake-3.6.1-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/renan/stm32f4-discovery-cmake && $(CMAKE_COMMAND) -E cmake_progress_start /home/renan/stm32f4-discovery-cmake/CMakeFiles /home/renan/stm32f4-discovery-cmake/roboime-firmware/CMakeFiles/progress.marks
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renan/stm32f4-discovery-cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/renan/stm32f4-discovery-cmake && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
roboime-firmware/CMakeFiles/utils_lib.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/utils_lib.dir/rule
.PHONY : roboime-firmware/CMakeFiles/utils_lib.dir/rule

# Convenience name for target.
utils_lib: roboime-firmware/CMakeFiles/utils_lib.dir/rule

.PHONY : utils_lib

# fast build rule for target.
utils_lib/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/build
.PHONY : utils_lib/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/rule
.PHONY : roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/rule

# Convenience name for target.
STM32F4xx_StdPeriph_Driver_libs: roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/rule

.PHONY : STM32F4xx_StdPeriph_Driver_libs

# fast build rule for target.
STM32F4xx_StdPeriph_Driver_libs/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build
.PHONY : STM32F4xx_StdPeriph_Driver_libs/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/usb_conf_libs.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/usb_conf_libs.dir/rule
.PHONY : roboime-firmware/CMakeFiles/usb_conf_libs.dir/rule

# Convenience name for target.
usb_conf_libs: roboime-firmware/CMakeFiles/usb_conf_libs.dir/rule

.PHONY : usb_conf_libs

# fast build rule for target.
usb_conf_libs/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/build
.PHONY : usb_conf_libs/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/rule
.PHONY : roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/rule

# Convenience name for target.
usb_lib_otg_libs: roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/rule

.PHONY : usb_lib_otg_libs

# fast build rule for target.
usb_lib_otg_libs/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build
.PHONY : usb_lib_otg_libs/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/roboime_fw_v1.0.bin.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/roboime_fw_v1.0.bin.dir/rule
.PHONY : roboime-firmware/CMakeFiles/roboime_fw_v1.0.bin.dir/rule

# Convenience name for target.
roboime_fw_v1.0.bin: roboime-firmware/CMakeFiles/roboime_fw_v1.0.bin.dir/rule

.PHONY : roboime_fw_v1.0.bin

# fast build rule for target.
roboime_fw_v1.0.bin/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/roboime_fw_v1.0.bin.dir/build.make roboime-firmware/CMakeFiles/roboime_fw_v1.0.bin.dir/build
.PHONY : roboime_fw_v1.0.bin/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/rule
.PHONY : roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/rule

# Convenience name for target.
usb_lib_cdc_libs: roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/rule

.PHONY : usb_lib_cdc_libs

# fast build rule for target.
usb_lib_cdc_libs/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build
.PHONY : usb_lib_cdc_libs/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/rule
.PHONY : roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/rule

# Convenience name for target.
usb_lib_core_libs: roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/rule

.PHONY : usb_lib_core_libs

# fast build rule for target.
usb_lib_core_libs/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build
.PHONY : usb_lib_core_libs/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/nrf_lib.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/nrf_lib.dir/rule
.PHONY : roboime-firmware/CMakeFiles/nrf_lib.dir/rule

# Convenience name for target.
nrf_lib: roboime-firmware/CMakeFiles/nrf_lib.dir/rule

.PHONY : nrf_lib

# fast build rule for target.
nrf_lib/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/build
.PHONY : nrf_lib/fast

# Convenience name for target.
roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/rule:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f CMakeFiles/Makefile2 roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/rule
.PHONY : roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/rule

# Convenience name for target.
roboime_fw_v1.0.elf: roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/rule

.PHONY : roboime_fw_v1.0.elf

# fast build rule for target.
roboime_fw_v1.0.elf/fast:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/build.make roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/build
.PHONY : roboime_fw_v1.0.elf/fast

lib/STM32F4xx_StdPeriph_Driver/src/misc.obj: lib/STM32F4xx_StdPeriph_Driver/src/misc.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/misc.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/misc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/misc.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/misc.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/misc.i: lib/STM32F4xx_StdPeriph_Driver/src/misc.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/misc.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/misc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/misc.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/misc.c.i

lib/STM32F4xx_StdPeriph_Driver/src/misc.s: lib/STM32F4xx_StdPeriph_Driver/src/misc.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/misc.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/misc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/misc.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/misc.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c.s

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.obj: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.obj

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.obj

# target to build an object file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.obj
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.obj

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.i: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.i

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.i

# target to preprocess a source file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.i
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.i

lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.s: lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.s

.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.s

# target to generate assembly for a file
lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/build.make roboime-firmware/CMakeFiles/STM32F4xx_StdPeriph_Driver_libs.dir/lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.s
.PHONY : lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c.s

lib/nrf/CONFIG.obj: lib/nrf/CONFIG.cpp.obj

.PHONY : lib/nrf/CONFIG.obj

# target to build an object file
lib/nrf/CONFIG.cpp.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/CONFIG.cpp.obj
.PHONY : lib/nrf/CONFIG.cpp.obj

lib/nrf/CONFIG.i: lib/nrf/CONFIG.cpp.i

.PHONY : lib/nrf/CONFIG.i

# target to preprocess a source file
lib/nrf/CONFIG.cpp.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/CONFIG.cpp.i
.PHONY : lib/nrf/CONFIG.cpp.i

lib/nrf/CONFIG.s: lib/nrf/CONFIG.cpp.s

.PHONY : lib/nrf/CONFIG.s

# target to generate assembly for a file
lib/nrf/CONFIG.cpp.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/CONFIG.cpp.s
.PHONY : lib/nrf/CONFIG.cpp.s

lib/nrf/NRF24.obj: lib/nrf/NRF24.cpp.obj

.PHONY : lib/nrf/NRF24.obj

# target to build an object file
lib/nrf/NRF24.cpp.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/NRF24.cpp.obj
.PHONY : lib/nrf/NRF24.cpp.obj

lib/nrf/NRF24.i: lib/nrf/NRF24.cpp.i

.PHONY : lib/nrf/NRF24.i

# target to preprocess a source file
lib/nrf/NRF24.cpp.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/NRF24.cpp.i
.PHONY : lib/nrf/NRF24.cpp.i

lib/nrf/NRF24.s: lib/nrf/NRF24.cpp.s

.PHONY : lib/nrf/NRF24.s

# target to generate assembly for a file
lib/nrf/NRF24.cpp.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/NRF24.cpp.s
.PHONY : lib/nrf/NRF24.cpp.s

lib/nrf/NRF_REGISTER_MAP.obj: lib/nrf/NRF_REGISTER_MAP.cpp.obj

.PHONY : lib/nrf/NRF_REGISTER_MAP.obj

# target to build an object file
lib/nrf/NRF_REGISTER_MAP.cpp.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/NRF_REGISTER_MAP.cpp.obj
.PHONY : lib/nrf/NRF_REGISTER_MAP.cpp.obj

lib/nrf/NRF_REGISTER_MAP.i: lib/nrf/NRF_REGISTER_MAP.cpp.i

.PHONY : lib/nrf/NRF_REGISTER_MAP.i

# target to preprocess a source file
lib/nrf/NRF_REGISTER_MAP.cpp.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/NRF_REGISTER_MAP.cpp.i
.PHONY : lib/nrf/NRF_REGISTER_MAP.cpp.i

lib/nrf/NRF_REGISTER_MAP.s: lib/nrf/NRF_REGISTER_MAP.cpp.s

.PHONY : lib/nrf/NRF_REGISTER_MAP.s

# target to generate assembly for a file
lib/nrf/NRF_REGISTER_MAP.cpp.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/NRF_REGISTER_MAP.cpp.s
.PHONY : lib/nrf/NRF_REGISTER_MAP.cpp.s

lib/nrf/REGISTER.obj: lib/nrf/REGISTER.cpp.obj

.PHONY : lib/nrf/REGISTER.obj

# target to build an object file
lib/nrf/REGISTER.cpp.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/REGISTER.cpp.obj
.PHONY : lib/nrf/REGISTER.cpp.obj

lib/nrf/REGISTER.i: lib/nrf/REGISTER.cpp.i

.PHONY : lib/nrf/REGISTER.i

# target to preprocess a source file
lib/nrf/REGISTER.cpp.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/REGISTER.cpp.i
.PHONY : lib/nrf/REGISTER.cpp.i

lib/nrf/REGISTER.s: lib/nrf/REGISTER.cpp.s

.PHONY : lib/nrf/REGISTER.s

# target to generate assembly for a file
lib/nrf/REGISTER.cpp.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/REGISTER.cpp.s
.PHONY : lib/nrf/REGISTER.cpp.s

lib/nrf/SPI_interface.obj: lib/nrf/SPI_interface.cpp.obj

.PHONY : lib/nrf/SPI_interface.obj

# target to build an object file
lib/nrf/SPI_interface.cpp.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/SPI_interface.cpp.obj
.PHONY : lib/nrf/SPI_interface.cpp.obj

lib/nrf/SPI_interface.i: lib/nrf/SPI_interface.cpp.i

.PHONY : lib/nrf/SPI_interface.i

# target to preprocess a source file
lib/nrf/SPI_interface.cpp.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/SPI_interface.cpp.i
.PHONY : lib/nrf/SPI_interface.cpp.i

lib/nrf/SPI_interface.s: lib/nrf/SPI_interface.cpp.s

.PHONY : lib/nrf/SPI_interface.s

# target to generate assembly for a file
lib/nrf/SPI_interface.cpp.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/nrf_lib.dir/build.make roboime-firmware/CMakeFiles/nrf_lib.dir/lib/nrf/SPI_interface.cpp.s
.PHONY : lib/nrf/SPI_interface.cpp.s

lib/usb_conf/usb_bsp.obj: lib/usb_conf/usb_bsp.c.obj

.PHONY : lib/usb_conf/usb_bsp.obj

# target to build an object file
lib/usb_conf/usb_bsp.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usb_bsp.c.obj
.PHONY : lib/usb_conf/usb_bsp.c.obj

lib/usb_conf/usb_bsp.i: lib/usb_conf/usb_bsp.c.i

.PHONY : lib/usb_conf/usb_bsp.i

# target to preprocess a source file
lib/usb_conf/usb_bsp.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usb_bsp.c.i
.PHONY : lib/usb_conf/usb_bsp.c.i

lib/usb_conf/usb_bsp.s: lib/usb_conf/usb_bsp.c.s

.PHONY : lib/usb_conf/usb_bsp.s

# target to generate assembly for a file
lib/usb_conf/usb_bsp.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usb_bsp.c.s
.PHONY : lib/usb_conf/usb_bsp.c.s

lib/usb_conf/usbd_desc.obj: lib/usb_conf/usbd_desc.c.obj

.PHONY : lib/usb_conf/usbd_desc.obj

# target to build an object file
lib/usb_conf/usbd_desc.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usbd_desc.c.obj
.PHONY : lib/usb_conf/usbd_desc.c.obj

lib/usb_conf/usbd_desc.i: lib/usb_conf/usbd_desc.c.i

.PHONY : lib/usb_conf/usbd_desc.i

# target to preprocess a source file
lib/usb_conf/usbd_desc.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usbd_desc.c.i
.PHONY : lib/usb_conf/usbd_desc.c.i

lib/usb_conf/usbd_desc.s: lib/usb_conf/usbd_desc.c.s

.PHONY : lib/usb_conf/usbd_desc.s

# target to generate assembly for a file
lib/usb_conf/usbd_desc.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usbd_desc.c.s
.PHONY : lib/usb_conf/usbd_desc.c.s

lib/usb_conf/usbd_usr.obj: lib/usb_conf/usbd_usr.c.obj

.PHONY : lib/usb_conf/usbd_usr.obj

# target to build an object file
lib/usb_conf/usbd_usr.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usbd_usr.c.obj
.PHONY : lib/usb_conf/usbd_usr.c.obj

lib/usb_conf/usbd_usr.i: lib/usb_conf/usbd_usr.c.i

.PHONY : lib/usb_conf/usbd_usr.i

# target to preprocess a source file
lib/usb_conf/usbd_usr.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usbd_usr.c.i
.PHONY : lib/usb_conf/usbd_usr.c.i

lib/usb_conf/usbd_usr.s: lib/usb_conf/usbd_usr.c.s

.PHONY : lib/usb_conf/usbd_usr.s

# target to generate assembly for a file
lib/usb_conf/usbd_usr.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_conf_libs.dir/build.make roboime-firmware/CMakeFiles/usb_conf_libs.dir/lib/usb_conf/usbd_usr.c.s
.PHONY : lib/usb_conf/usbd_usr.c.s

lib/usb_lib/cdc/usbd_cdc_core.obj: lib/usb_lib/cdc/usbd_cdc_core.c.obj

.PHONY : lib/usb_lib/cdc/usbd_cdc_core.obj

# target to build an object file
lib/usb_lib/cdc/usbd_cdc_core.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/lib/usb_lib/cdc/usbd_cdc_core.c.obj
.PHONY : lib/usb_lib/cdc/usbd_cdc_core.c.obj

lib/usb_lib/cdc/usbd_cdc_core.i: lib/usb_lib/cdc/usbd_cdc_core.c.i

.PHONY : lib/usb_lib/cdc/usbd_cdc_core.i

# target to preprocess a source file
lib/usb_lib/cdc/usbd_cdc_core.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/lib/usb_lib/cdc/usbd_cdc_core.c.i
.PHONY : lib/usb_lib/cdc/usbd_cdc_core.c.i

lib/usb_lib/cdc/usbd_cdc_core.s: lib/usb_lib/cdc/usbd_cdc_core.c.s

.PHONY : lib/usb_lib/cdc/usbd_cdc_core.s

# target to generate assembly for a file
lib/usb_lib/cdc/usbd_cdc_core.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/lib/usb_lib/cdc/usbd_cdc_core.c.s
.PHONY : lib/usb_lib/cdc/usbd_cdc_core.c.s

lib/usb_lib/cdc/usbd_cdc_vcp.obj: lib/usb_lib/cdc/usbd_cdc_vcp.c.obj

.PHONY : lib/usb_lib/cdc/usbd_cdc_vcp.obj

# target to build an object file
lib/usb_lib/cdc/usbd_cdc_vcp.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/lib/usb_lib/cdc/usbd_cdc_vcp.c.obj
.PHONY : lib/usb_lib/cdc/usbd_cdc_vcp.c.obj

lib/usb_lib/cdc/usbd_cdc_vcp.i: lib/usb_lib/cdc/usbd_cdc_vcp.c.i

.PHONY : lib/usb_lib/cdc/usbd_cdc_vcp.i

# target to preprocess a source file
lib/usb_lib/cdc/usbd_cdc_vcp.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/lib/usb_lib/cdc/usbd_cdc_vcp.c.i
.PHONY : lib/usb_lib/cdc/usbd_cdc_vcp.c.i

lib/usb_lib/cdc/usbd_cdc_vcp.s: lib/usb_lib/cdc/usbd_cdc_vcp.c.s

.PHONY : lib/usb_lib/cdc/usbd_cdc_vcp.s

# target to generate assembly for a file
lib/usb_lib/cdc/usbd_cdc_vcp.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_cdc_libs.dir/lib/usb_lib/cdc/usbd_cdc_vcp.c.s
.PHONY : lib/usb_lib/cdc/usbd_cdc_vcp.c.s

lib/usb_lib/core/usbd_core.obj: lib/usb_lib/core/usbd_core.c.obj

.PHONY : lib/usb_lib/core/usbd_core.obj

# target to build an object file
lib/usb_lib/core/usbd_core.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_core.c.obj
.PHONY : lib/usb_lib/core/usbd_core.c.obj

lib/usb_lib/core/usbd_core.i: lib/usb_lib/core/usbd_core.c.i

.PHONY : lib/usb_lib/core/usbd_core.i

# target to preprocess a source file
lib/usb_lib/core/usbd_core.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_core.c.i
.PHONY : lib/usb_lib/core/usbd_core.c.i

lib/usb_lib/core/usbd_core.s: lib/usb_lib/core/usbd_core.c.s

.PHONY : lib/usb_lib/core/usbd_core.s

# target to generate assembly for a file
lib/usb_lib/core/usbd_core.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_core.c.s
.PHONY : lib/usb_lib/core/usbd_core.c.s

lib/usb_lib/core/usbd_ioreq.obj: lib/usb_lib/core/usbd_ioreq.c.obj

.PHONY : lib/usb_lib/core/usbd_ioreq.obj

# target to build an object file
lib/usb_lib/core/usbd_ioreq.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_ioreq.c.obj
.PHONY : lib/usb_lib/core/usbd_ioreq.c.obj

lib/usb_lib/core/usbd_ioreq.i: lib/usb_lib/core/usbd_ioreq.c.i

.PHONY : lib/usb_lib/core/usbd_ioreq.i

# target to preprocess a source file
lib/usb_lib/core/usbd_ioreq.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_ioreq.c.i
.PHONY : lib/usb_lib/core/usbd_ioreq.c.i

lib/usb_lib/core/usbd_ioreq.s: lib/usb_lib/core/usbd_ioreq.c.s

.PHONY : lib/usb_lib/core/usbd_ioreq.s

# target to generate assembly for a file
lib/usb_lib/core/usbd_ioreq.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_ioreq.c.s
.PHONY : lib/usb_lib/core/usbd_ioreq.c.s

lib/usb_lib/core/usbd_req.obj: lib/usb_lib/core/usbd_req.c.obj

.PHONY : lib/usb_lib/core/usbd_req.obj

# target to build an object file
lib/usb_lib/core/usbd_req.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_req.c.obj
.PHONY : lib/usb_lib/core/usbd_req.c.obj

lib/usb_lib/core/usbd_req.i: lib/usb_lib/core/usbd_req.c.i

.PHONY : lib/usb_lib/core/usbd_req.i

# target to preprocess a source file
lib/usb_lib/core/usbd_req.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_req.c.i
.PHONY : lib/usb_lib/core/usbd_req.c.i

lib/usb_lib/core/usbd_req.s: lib/usb_lib/core/usbd_req.c.s

.PHONY : lib/usb_lib/core/usbd_req.s

# target to generate assembly for a file
lib/usb_lib/core/usbd_req.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_core_libs.dir/lib/usb_lib/core/usbd_req.c.s
.PHONY : lib/usb_lib/core/usbd_req.c.s

lib/usb_lib/otg/usb_core.obj: lib/usb_lib/otg/usb_core.c.obj

.PHONY : lib/usb_lib/otg/usb_core.obj

# target to build an object file
lib/usb_lib/otg/usb_core.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_core.c.obj
.PHONY : lib/usb_lib/otg/usb_core.c.obj

lib/usb_lib/otg/usb_core.i: lib/usb_lib/otg/usb_core.c.i

.PHONY : lib/usb_lib/otg/usb_core.i

# target to preprocess a source file
lib/usb_lib/otg/usb_core.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_core.c.i
.PHONY : lib/usb_lib/otg/usb_core.c.i

lib/usb_lib/otg/usb_core.s: lib/usb_lib/otg/usb_core.c.s

.PHONY : lib/usb_lib/otg/usb_core.s

# target to generate assembly for a file
lib/usb_lib/otg/usb_core.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_core.c.s
.PHONY : lib/usb_lib/otg/usb_core.c.s

lib/usb_lib/otg/usb_dcd.obj: lib/usb_lib/otg/usb_dcd.c.obj

.PHONY : lib/usb_lib/otg/usb_dcd.obj

# target to build an object file
lib/usb_lib/otg/usb_dcd.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_dcd.c.obj
.PHONY : lib/usb_lib/otg/usb_dcd.c.obj

lib/usb_lib/otg/usb_dcd.i: lib/usb_lib/otg/usb_dcd.c.i

.PHONY : lib/usb_lib/otg/usb_dcd.i

# target to preprocess a source file
lib/usb_lib/otg/usb_dcd.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_dcd.c.i
.PHONY : lib/usb_lib/otg/usb_dcd.c.i

lib/usb_lib/otg/usb_dcd.s: lib/usb_lib/otg/usb_dcd.c.s

.PHONY : lib/usb_lib/otg/usb_dcd.s

# target to generate assembly for a file
lib/usb_lib/otg/usb_dcd.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_dcd.c.s
.PHONY : lib/usb_lib/otg/usb_dcd.c.s

lib/usb_lib/otg/usb_dcd_int.obj: lib/usb_lib/otg/usb_dcd_int.c.obj

.PHONY : lib/usb_lib/otg/usb_dcd_int.obj

# target to build an object file
lib/usb_lib/otg/usb_dcd_int.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_dcd_int.c.obj
.PHONY : lib/usb_lib/otg/usb_dcd_int.c.obj

lib/usb_lib/otg/usb_dcd_int.i: lib/usb_lib/otg/usb_dcd_int.c.i

.PHONY : lib/usb_lib/otg/usb_dcd_int.i

# target to preprocess a source file
lib/usb_lib/otg/usb_dcd_int.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_dcd_int.c.i
.PHONY : lib/usb_lib/otg/usb_dcd_int.c.i

lib/usb_lib/otg/usb_dcd_int.s: lib/usb_lib/otg/usb_dcd_int.c.s

.PHONY : lib/usb_lib/otg/usb_dcd_int.s

# target to generate assembly for a file
lib/usb_lib/otg/usb_dcd_int.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/build.make roboime-firmware/CMakeFiles/usb_lib_otg_libs.dir/lib/usb_lib/otg/usb_dcd_int.c.s
.PHONY : lib/usb_lib/otg/usb_dcd_int.c.s

lib/utils/stm32f4_discovery/stm32f4_discovery.obj: lib/utils/stm32f4_discovery/stm32f4_discovery.c.obj

.PHONY : lib/utils/stm32f4_discovery/stm32f4_discovery.obj

# target to build an object file
lib/utils/stm32f4_discovery/stm32f4_discovery.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4_discovery/stm32f4_discovery.c.obj
.PHONY : lib/utils/stm32f4_discovery/stm32f4_discovery.c.obj

lib/utils/stm32f4_discovery/stm32f4_discovery.i: lib/utils/stm32f4_discovery/stm32f4_discovery.c.i

.PHONY : lib/utils/stm32f4_discovery/stm32f4_discovery.i

# target to preprocess a source file
lib/utils/stm32f4_discovery/stm32f4_discovery.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4_discovery/stm32f4_discovery.c.i
.PHONY : lib/utils/stm32f4_discovery/stm32f4_discovery.c.i

lib/utils/stm32f4_discovery/stm32f4_discovery.s: lib/utils/stm32f4_discovery/stm32f4_discovery.c.s

.PHONY : lib/utils/stm32f4_discovery/stm32f4_discovery.s

# target to generate assembly for a file
lib/utils/stm32f4_discovery/stm32f4_discovery.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4_discovery/stm32f4_discovery.c.s
.PHONY : lib/utils/stm32f4_discovery/stm32f4_discovery.c.s

lib/utils/stm32f4xx/stm32f4xx_it.obj: lib/utils/stm32f4xx/stm32f4xx_it.c.obj

.PHONY : lib/utils/stm32f4xx/stm32f4xx_it.obj

# target to build an object file
lib/utils/stm32f4xx/stm32f4xx_it.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/stm32f4xx_it.c.obj
.PHONY : lib/utils/stm32f4xx/stm32f4xx_it.c.obj

lib/utils/stm32f4xx/stm32f4xx_it.i: lib/utils/stm32f4xx/stm32f4xx_it.c.i

.PHONY : lib/utils/stm32f4xx/stm32f4xx_it.i

# target to preprocess a source file
lib/utils/stm32f4xx/stm32f4xx_it.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/stm32f4xx_it.c.i
.PHONY : lib/utils/stm32f4xx/stm32f4xx_it.c.i

lib/utils/stm32f4xx/stm32f4xx_it.s: lib/utils/stm32f4xx/stm32f4xx_it.c.s

.PHONY : lib/utils/stm32f4xx/stm32f4xx_it.s

# target to generate assembly for a file
lib/utils/stm32f4xx/stm32f4xx_it.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/stm32f4xx_it.c.s
.PHONY : lib/utils/stm32f4xx/stm32f4xx_it.c.s

lib/utils/stm32f4xx/system_stm32f4xx.obj: lib/utils/stm32f4xx/system_stm32f4xx.c.obj

.PHONY : lib/utils/stm32f4xx/system_stm32f4xx.obj

# target to build an object file
lib/utils/stm32f4xx/system_stm32f4xx.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/system_stm32f4xx.c.obj
.PHONY : lib/utils/stm32f4xx/system_stm32f4xx.c.obj

lib/utils/stm32f4xx/system_stm32f4xx.i: lib/utils/stm32f4xx/system_stm32f4xx.c.i

.PHONY : lib/utils/stm32f4xx/system_stm32f4xx.i

# target to preprocess a source file
lib/utils/stm32f4xx/system_stm32f4xx.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/system_stm32f4xx.c.i
.PHONY : lib/utils/stm32f4xx/system_stm32f4xx.c.i

lib/utils/stm32f4xx/system_stm32f4xx.s: lib/utils/stm32f4xx/system_stm32f4xx.c.s

.PHONY : lib/utils/stm32f4xx/system_stm32f4xx.s

# target to generate assembly for a file
lib/utils/stm32f4xx/system_stm32f4xx.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/system_stm32f4xx.c.s
.PHONY : lib/utils/stm32f4xx/system_stm32f4xx.c.s

lib/utils/stm32f4xx/tiny_printf.obj: lib/utils/stm32f4xx/tiny_printf.c.obj

.PHONY : lib/utils/stm32f4xx/tiny_printf.obj

# target to build an object file
lib/utils/stm32f4xx/tiny_printf.c.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/tiny_printf.c.obj
.PHONY : lib/utils/stm32f4xx/tiny_printf.c.obj

lib/utils/stm32f4xx/tiny_printf.i: lib/utils/stm32f4xx/tiny_printf.c.i

.PHONY : lib/utils/stm32f4xx/tiny_printf.i

# target to preprocess a source file
lib/utils/stm32f4xx/tiny_printf.c.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/tiny_printf.c.i
.PHONY : lib/utils/stm32f4xx/tiny_printf.c.i

lib/utils/stm32f4xx/tiny_printf.s: lib/utils/stm32f4xx/tiny_printf.c.s

.PHONY : lib/utils/stm32f4xx/tiny_printf.s

# target to generate assembly for a file
lib/utils/stm32f4xx/tiny_printf.c.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/utils_lib.dir/build.make roboime-firmware/CMakeFiles/utils_lib.dir/lib/utils/stm32f4xx/tiny_printf.c.s
.PHONY : lib/utils/stm32f4xx/tiny_printf.c.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/build.make roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/build.make roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	cd /home/renan/stm32f4-discovery-cmake && $(MAKE) -f roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/build.make roboime-firmware/CMakeFiles/roboime_fw_v1.0.elf.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... utils_lib"
	@echo "... STM32F4xx_StdPeriph_Driver_libs"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... usb_conf_libs"
	@echo "... usb_lib_otg_libs"
	@echo "... roboime_fw_v1.0.bin"
	@echo "... usb_lib_cdc_libs"
	@echo "... usb_lib_core_libs"
	@echo "... nrf_lib"
	@echo "... roboime_fw_v1.0.elf"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/misc.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/misc.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/misc.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.s"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.obj"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.i"
	@echo "... lib/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.s"
	@echo "... lib/nrf/CONFIG.obj"
	@echo "... lib/nrf/CONFIG.i"
	@echo "... lib/nrf/CONFIG.s"
	@echo "... lib/nrf/NRF24.obj"
	@echo "... lib/nrf/NRF24.i"
	@echo "... lib/nrf/NRF24.s"
	@echo "... lib/nrf/NRF_REGISTER_MAP.obj"
	@echo "... lib/nrf/NRF_REGISTER_MAP.i"
	@echo "... lib/nrf/NRF_REGISTER_MAP.s"
	@echo "... lib/nrf/REGISTER.obj"
	@echo "... lib/nrf/REGISTER.i"
	@echo "... lib/nrf/REGISTER.s"
	@echo "... lib/nrf/SPI_interface.obj"
	@echo "... lib/nrf/SPI_interface.i"
	@echo "... lib/nrf/SPI_interface.s"
	@echo "... lib/usb_conf/usb_bsp.obj"
	@echo "... lib/usb_conf/usb_bsp.i"
	@echo "... lib/usb_conf/usb_bsp.s"
	@echo "... lib/usb_conf/usbd_desc.obj"
	@echo "... lib/usb_conf/usbd_desc.i"
	@echo "... lib/usb_conf/usbd_desc.s"
	@echo "... lib/usb_conf/usbd_usr.obj"
	@echo "... lib/usb_conf/usbd_usr.i"
	@echo "... lib/usb_conf/usbd_usr.s"
	@echo "... lib/usb_lib/cdc/usbd_cdc_core.obj"
	@echo "... lib/usb_lib/cdc/usbd_cdc_core.i"
	@echo "... lib/usb_lib/cdc/usbd_cdc_core.s"
	@echo "... lib/usb_lib/cdc/usbd_cdc_vcp.obj"
	@echo "... lib/usb_lib/cdc/usbd_cdc_vcp.i"
	@echo "... lib/usb_lib/cdc/usbd_cdc_vcp.s"
	@echo "... lib/usb_lib/core/usbd_core.obj"
	@echo "... lib/usb_lib/core/usbd_core.i"
	@echo "... lib/usb_lib/core/usbd_core.s"
	@echo "... lib/usb_lib/core/usbd_ioreq.obj"
	@echo "... lib/usb_lib/core/usbd_ioreq.i"
	@echo "... lib/usb_lib/core/usbd_ioreq.s"
	@echo "... lib/usb_lib/core/usbd_req.obj"
	@echo "... lib/usb_lib/core/usbd_req.i"
	@echo "... lib/usb_lib/core/usbd_req.s"
	@echo "... lib/usb_lib/otg/usb_core.obj"
	@echo "... lib/usb_lib/otg/usb_core.i"
	@echo "... lib/usb_lib/otg/usb_core.s"
	@echo "... lib/usb_lib/otg/usb_dcd.obj"
	@echo "... lib/usb_lib/otg/usb_dcd.i"
	@echo "... lib/usb_lib/otg/usb_dcd.s"
	@echo "... lib/usb_lib/otg/usb_dcd_int.obj"
	@echo "... lib/usb_lib/otg/usb_dcd_int.i"
	@echo "... lib/usb_lib/otg/usb_dcd_int.s"
	@echo "... lib/utils/stm32f4_discovery/stm32f4_discovery.obj"
	@echo "... lib/utils/stm32f4_discovery/stm32f4_discovery.i"
	@echo "... lib/utils/stm32f4_discovery/stm32f4_discovery.s"
	@echo "... lib/utils/stm32f4xx/stm32f4xx_it.obj"
	@echo "... lib/utils/stm32f4xx/stm32f4xx_it.i"
	@echo "... lib/utils/stm32f4xx/stm32f4xx_it.s"
	@echo "... lib/utils/stm32f4xx/system_stm32f4xx.obj"
	@echo "... lib/utils/stm32f4xx/system_stm32f4xx.i"
	@echo "... lib/utils/stm32f4xx/system_stm32f4xx.s"
	@echo "... lib/utils/stm32f4xx/tiny_printf.obj"
	@echo "... lib/utils/stm32f4xx/tiny_printf.i"
	@echo "... lib/utils/stm32f4xx/tiny_printf.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/renan/stm32f4-discovery-cmake && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

